### PR TITLE
docs: new screenshot

### PR DESCRIPTION
**Pull request by NamesCode**
Updated screenshot

### CODE REVIEW

**Comment by nekowinston** [comment]
Closes issue #7 when adapted.

> Please also keep the original (one for each flavour) screenshots in ./assets.

Do you still have the per-flavour screenshots?

**Comment by NamesCode** [comment]
yep
I can send to you on discord if needed

**Comment by nekowinston** [comment]
Could you please just add them as `./assets/{latte,frappe,macchiato,mocha}.webp` in this PR?

**Comment by NamesCode** [comment]
Done, should be ready to merge hopefully

**Comment by NamesCode** [comment]
Sorry for late response

**Comment by nekowinston** [comment]
No worries, thanks for updating the screenshots as well!

**Pull request merged**
